name: Build Test
on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
      - run: go version
      - run: go test -v github.com/jc-lab/signed-json/...
