name: Build Test
on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
      - run: go version
      - run: go test -v github.com/jc-lab/signed-json/...
  java-build:
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11']
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build
        run: |
          cd java
          chmod +x gradlew
          ./gradlew build test
